name: Test
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
  short:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20
          - 18
          - 16
          - 14
          - 12
          - 10
          - 8
    name: Node.js ${{ matrix.node-version }} Quick
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
      - name: Run unit tests
        run: yarn test
